---
distFolder: build_production
setup:
- name: Setup composer
  action: php-actions/composer@v2
- name: Setup Node.js
  action: actions/setup-node@v1
  properties:
    node-version: v10.16.3
prepare:
  name: Prepare Project build environment
  command: npm ci
build:
  name: Build Jigsaw
  command: npm run production